from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('./board_config/*.c') 
CPPPATH = [cwd, os.path.join(cwd,'board_config'), os.path.join(cwd,'test_data')]

for i in CPPPATH:
    print(i)

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
